services:
 
  redis:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    ports:
      - "6381:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"] 
      interval: 10s 
      timeout: 5s 
      retries: 5 

  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: volunteer_camp
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5674:5672"
      - "15674:15672"
    restart: unless-stopped
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  redis-data:
  mysql-data:
  rabbitmq-data:
